### ISSUE TITLE
Failed to Execute

### ISSUE THREAD

**Issue by martinvahi** [tomfran/search-rs#1]
Tested it on Windows Subsystem for Linux (WSL) with a command

    RUST_BACKTRACE=full make cli folder=/mnt/d/Martin/dokumentatsioon/minu_konspektide_sorkkoopia/mmmvkos2_sorkkoopia action=build min_f=1 max_p=0.99       

The result:

    thread 'main' panicked at search/src/engine/builder.rs:45:10:
    error while retrieving input directory content: Os { code: 2, kind: NotFound, message: "No such file or directory" }
    stack backtrace:
       0:     0x5636c32d2e2c - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
       1:     0x5636c32d2e2c - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
       2:     0x5636c32d2e2c - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
       3:     0x5636c32d2e2c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
       4:     0x5636c32fe640 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
       5:     0x5636c32fe640 - core::fmt::write::h3a39390d8560d9c9
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
       6:     0x5636c32d072f - std::io::Write::write_fmt::h5fc9997dfe05f882
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
       7:     0x5636c32d2c14 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
       8:     0x5636c32d2c14 - std::sys_common::backtrace::print::h23a2d212c6fff936
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
       9:     0x5636c32d43c7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
      10:     0x5636c32d412f - std::panicking::default_hook::h6038f2eba384e475
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
      11:     0x5636c32d4848 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
      12:     0x5636c32d472e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
      13:     0x5636c32d32f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
      14:     0x5636c32d4492 - rust_begin_unwind
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
      15:     0x5636c3193165 - core::panicking::panic_fmt::hbf0e066aabfa482c
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
      16:     0x5636c3193643 - core::result::unwrap_failed::hddb4fea594200c52
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
      17:     0x5636c31a53d4 - search::engine::builder::build_engine::hbbcef932f9a97986
      18:     0x5636c319900d - search::engine::Engine::build_engine::h271921d979f86d42
      19:     0x5636c3195da1 - search::main::hc02049b8abf316b9
      20:     0x5636c3196123 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7d241be823446d89
      21:     0x5636c3196159 - std::rt::lang_start::{{closure}}::he01723b8fe6f4c68
      22:     0x5636c32c9cc7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
      23:     0x5636c32c9cc7 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      24:     0x5636c32c9cc7 - std::panicking::try::h3a52eefe24fe3c29
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      25:     0x5636c32c9cc7 - std::panic::catch_unwind::h24c28c23c02c3841
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      26:     0x5636c32c9cc7 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
      27:     0x5636c32c9cc7 - std::panicking::try::do_call::ha21f52ba13158470
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
      28:     0x5636c32c9cc7 - std::panicking::try::h5581346bf6aeb1f8
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
      29:     0x5636c32c9cc7 - std::panic::catch_unwind::h7919645a6b72e25b
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
      30:     0x5636c32c9cc7 - std::rt::lang_start_internal::h12de51168669836e
                                   at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
      31:     0x5636c319614e - std::rt::lang_start::hf1c03709220f7fca
      32:     0x7fc8a9656d0a - __libc_start_main
      33:     0x5636c319390a - _start
      34:                0x0 - <unknown>
    make: *** [makefile:5: cli] Error 101
    mmmv@DESKTOP-H12EA8D:~/m_local/bin_p/search_rs/kompil/search-rs$

**Comment by tomfran** [comment]
Hi, what's the content of that directory? The main assumes the docs to be processed are located in a `/docs` subfolder.

Can you confirm you have the folder: `.../mmmvkos2_sorkkoopia/docs`, containing only text documents?

By the way, I just updated the builder and main to account for subfolders and remove this constraint. Feel free to pull latest changes and retry. Have a read at the readme to understand what will be skipped on indexing and where the index will be placed.
